### PR TITLE
fix egan protobrain crash

### LINKED ISSUE #297: egan protobrain crash
> 08-31 11:44:21, Info: score 0
08-31 11:44:21, Info: OnStep: 1
panic: runtime error: slice bounds out of range [:1] with capacity 0

goroutine 82 [running]:
github.com/emer/etable/etensor.(*Float32).SubSpaceTry(0xc000bd1d80, {0xc01600d328, 0x2, 0x3?})
	/home/erdal/go/pkg/mod/github.com/emer/etable@v1.1.8/etensor/numeric.gen.go:2634 +0x5bd
github.com/emer/etable/etensor.(*Float32).SubSpace(...)
	/home/erdal/go/pkg/mod/github.com/emer/etable@v1.1.8/etensor/numeric.gen.go:2607
main.(*World).fillFovPatterns(0xc0000b8500, {0xc0004f70c0, 0x3, 0x4?}, 0x3)
	/home/erdal/dev/obelisk/obelisk/models/integrated/egan_protobrain/egan.go:158 +0x92
main.(*World).GetAllObservations(0xc0000b8500)
	/home/erdal/dev/obelisk/obelisk/models/integrated/egan_protobrain/egan.go:199 +0x1c6
main.(*Sim).OnObserve(0xc000514000)
	/home/erdal/dev/obelisk/obelisk/models/integrated/egan_protobrain/protobrain.go:158 +0x155
github.com/emer/emergent/looper.(*Manager).runLevel(0xc0004f6a40, 0x2)
	/home/erdal/dev/obelisk/obelisk/emergent/looper/manager.go:254 +0x7f4
github.com/emer/emergent/looper.(*Manager).runLevel(0xc0004f6a40, 0x1)
	/home/erdal/dev/obelisk/obelisk/emergent/looper/manager.go:261 +0x42f
github.com/emer/emergent/looper.(*Manager).runLevel(0xc0004f6a40, 0x0)
	/home/erdal/dev/obelisk/obelisk/emergent/looper/manager.go:261 +0x42f
github.com/emer/emergent/looper.(*Manager).Cont(...)
	/home/erdal/dev/obelisk/obelisk/emergent/looper/manager.go:203
github.com/emer/emergent/looper.(*Manager).Step(0xc0004f6a40, 0x2?, 0x1, 0xa)
	/home/erdal/dev/obelisk/obelisk/emergent/looper/manager.go:169 +0x7b
main.(*Sim).OnStep(0xc000514000, 0xc000619200)
	/home/erdal/dev/obelisk/obelisk/models/integrated/egan_protobrain/protobrain.go:184 +0x32f
github.com/Astera-org/obelisk/models/agent.(*NetworkAgent).Step(0xc0004e0020, {0xc0001ade00?, 0xc000c0c060?}, 0x19381e8?, {0xc0003d2000?, 0x1308b79?})
	/home/erdal/dev/obelisk/obelisk/models/agent/network_agent.go:50 +0x10e
github.com/Astera-org/obelisk/network/gengo/env.(*agentServiceProcessorStep).Process(0xc0000338d0, {0x19213c0, 0xc000c0c060}, 0x4?, {0x19381e8?, 0xc0003d2000}, {0x19381e8, 0xc0003d2070})
	/home/erdal/dev/obelisk/obelisk/network/gengo/env/env.go:1394 +0x2d2
github.com/Astera-org/obelisk/network/gengo/env.(*AgentServiceProcessor).Process(0xc0004d8048, {0x19213c0, 0xc000c0c060}, {0x19381e8, 0xc0003d2000}, {0x19381e8?, 0xc0003d2070?})
	/home/erdal/dev/obelisk/obelisk/network/gengo/env/env.go:1335 +0x27d
github.com/apache/thrift/lib/go/thrift.(*TSimpleServer).processRequests(0xc0005ae500, {0x19253a0, 0xc000328360})
	/home/erdal/go/pkg/mod/github.com/apache/thrift@v0.16.0/lib/go/thrift/simple_server.go:320 +0x5ca
github.com/apache/thrift/lib/go/thrift.(*TSimpleServer).innerAccept.func1()
	/home/erdal/go/pkg/mod/github.com/apache/thrift@v0.16.0/lib/go/thrift/simple_server.go:198 +0x6b
created by github.com/apache/thrift/lib/go/thrift.(*TSimpleServer).innerAccept
	/home/erdal/go/pkg/mod/github.com/apache/thrift@v0.16.0/lib/go/thrift/simple_server.go:196 +0x165
exit status 2

### PR DESCRIPTION
**Pull request by etuleu**
Fixes #297

### CODE REVIEW

File: models/integrated/egan_protobrain/egan.go [hunk 1]
```diff
@@ -330,7 +333,7 @@ func (w *World) Config() {
 func (w *World) openPats(filename gi.FileName) error {
 	fp, err := os.Open(string(filename))
 	if err != nil {
-		fmt.Println("ERROR! Can't find pats file! This will prevent the model from working! :", err)
+		panic("ERROR! Can't find pats file! This will prevent the model from working!")
```
Comment (jedmccaleb) [inline models/integrated/egan_protobrain/egan.go:336]: can you use log.Fatal

File: models/integrated/egan_protobrain/protobrain.go [hunk 2]
```diff
@@ -153,17 +151,23 @@ func (ss *Sim) OnObserve() {
...
 	}
 }
 
 func (ss *Sim) OnStep(obs map[string]etensor.Tensor) map[string]agent.Action {
+	log.Info("OnStep step: ", ss.NumSteps, " obs: ", obs)
+
+	ss.WorldEnv.(*agent.NetworkWorld).SetObservations(obs)
+
+	ss.Loops.Step(ss.Loops.Mode, 1, etime.Trial)
+	// sim.AddActionHistory(obs, etime.Trial.String()) //record history as discrete values
```
Comment (garymm) [inline models/integrated/egan_protobrain/protobrain.go:170]: can we remove? Or is this useful to keep?

File: models/integrated/egan_protobrain/BUILD.bazel [hunk 3]
```diff
@@ -38,6 +38,10 @@ go_binary(
 go_test(
     name = "egan_protobrain_test",
     srcs = ["egan_test.go"],
+    data = [
+        "package/default.cfg",
```
Comment (garymm) [inline models/integrated/egan_protobrain/BUILD.bazel:42]: this file doesn't exist, which is why `bazel test //models/integrated/egan_protobrain:egan_protobrain_test`  failed

**Review by garymm — CHANGES_REQUESTED** [review]

File: models/integrated/egan_protobrain/package/default.cfg [hunk 4]
```diff
@@ -0,0 +1,5 @@
+GUI=false
```
Comment (garymm) [inline models/integrated/egan_protobrain/package/default.cfg:1]: nit, can we be consistent about surrounding `=` with spaces or not?

File: models/integrated/egan_protobrain/package/default.cfg [hunk 5]
```diff
@@ -0,0 +1,5 @@
...
+PROFILE=false
+LIFETIME=25
+LRATE = 0.01
+ACTAVG_INIT = 0.06
```
Comment (garymm) [inline models/integrated/egan_protobrain/package/default.cfg:5]: please add a trailing newline. Otherwise it's not a valid text file according to Unix.

File: models/integrated/egan_protobrain/protobrain.go [hunk 6]
```diff
@@ -153,17 +151,22 @@ func (ss *Sim) OnObserve() {
 	// agent is located in the middle of the bottom row
 	w := World{Pixels: pixels.(*etensor.Float64), AgentX: x / 2, AgentY: 0, WorldX: x, WorldY: y}
 	w.Config()
-	// fmt.Println("Received egan world: ", w.Fv)
+	// log.Info("world: ", w)
```
Comment (garymm) [inline models/integrated/egan_protobrain/protobrain.go:154]: remove?

**Review by garymm — APPROVED** [review]
