### PR TITLE
handle binary missing

### LINKED ISSUE #192: Job status is still working if the binary fetching fails
To reproduce put in the wrong port for binserver in the worker config or bring down binserver. The binary download will fail but the job status will not be updated, so it will forever remain in the working state.

Solution:
Probably just need to handle this error and update the job as failed.

### PR DESCRIPTION
**Pull request by etuleu**
Fixes #192

### CODE REVIEW

File: infra/worker/job.go [hunk 1]
```diff
@@ -42,30 +42,34 @@ func (job *Job) fetchWork() error {
...
+	agentBinInfo, err := gApp.binCache.EnsureBinary(job.AgentID)
+	if err != nil {
 		job.Result.Status = jobFailed
-		return errors.New(fmt.Sprint("agent not found ", infraJob.AgentID))
+		return errors.New(fmt.Sprint("agent not found ", job.AgentID))
 	}
+
 	job.AgentBinPath = getLocalPath(agentBinInfo)
-	worldBinInfo := gApp.binCache.EnsureBinary(infraJob.WorldID)
+	worldBinInfo, err := gApp.binCache.EnsureBinary(job.WorldID)
```
Comment (jedmccaleb) [inline infra/worker/job.go:64]: Does this work if there is not a world required?

Comment (etuleu) [reply infra/worker/job.go:64]: I think so. In this case the logic hasn't changed. I just used the more goey pattern for returning a value and an error.

**Review by jedmccaleb — APPROVED** [review]

File: infra/worker/job.go (hunk 1 above)
Comment (jedmccaleb) [reply infra/worker/job.go:64]: ok we aren't doing anything with err
