### PR TITLE
Handle http server errors

### LINKED ISSUE #193: http server silently fails to start if the port is already in use
This happened to me locally because both binserver and odpw are using port 8080 by default.

And this can happen in prod as well if we have zombie processes which will inevitably happen.

Solution: listen for the error code from the http start goroutine and panic if it arrives.

### PR DESCRIPTION
**Pull request by etuleu**
Fixes #193 

Unrelated changes:
1. init the log file before loading config because in case of an error the program panics because the log file is not ready yet.
2. Handle weird input signals that happen in the background in the services that were missing it. This helps with local testing.
3. Update run_local script to also start binserver and odpw and to log errors during startup to a file. This was needed because odpw was not starting and the error was not shown when testing locally.

### CODE REVIEW

File: infra/binserver/binserver.go [hunk 1]
```diff
@@ -29,6 +29,8 @@ func main() {
 		panic(err)
 	}
 
+	gConfig.Load()
```
Comment (jedmccaleb) [inline infra/binserver/binserver.go:32]: I did this before on purpose since there could be config entries that effect the log initiation. gConfig.load shouldn't use log

File: infra/jobczar/jobczar.go [hunk 2]
```diff
@@ -49,6 +47,8 @@ func main() {
 		panic(err)
 	}
 
+	gConfig.Load()
```
Comment (jedmccaleb) [inline infra/jobczar/jobczar.go:50]: same here

File: infra/odpw/odpw.go [hunk 3]
```diff
@@ -25,6 +25,8 @@ func main() {
 		panic(err)
 	}
 
+	gConfig.Load()
```
Comment (jedmccaleb) [inline infra/odpw/odpw.go:28]: same here

File: infra/worker/config.go [hunk 4]
```diff
@@ -42,8 +42,8 @@ func (config *Config) setDefaults() {
 	config.WINDOWS = false
 
 	config.JOBCZAR_IP = "127.0.0.1"
-	config.BINSERVER_URL = "127.0.0.1:9003"
-	config.JOBCZAR_PORT = 9001
+	config.BINSERVER_URL = "127.0.0.1:8080"
```
Comment (jedmccaleb) [inline infra/worker/config.go:45]: I was changing it to what it is in the cluster

File: infra/worker/worker.go [hunk 5]
```diff
@@ -42,6 +36,12 @@ func main() {
 		panic(err)
 	}
 
+	gConfig.Load()
```
Comment (jedmccaleb) [inline infra/worker/worker.go:39]: same here

File: infra/worker/config.go (hunk 4 above)
Comment (etuleu) [reply infra/worker/config.go:45]: Oh I didn't mean to push this file

File: infra/binserver/binserver.go (hunk 1 above)
Comment (etuleu) [reply infra/binserver/binserver.go:32]: Ah I see. Will revert and make sure it doesn't use log.

File: infra/odpw/odpw.go (hunk 3 above)
Comment (etuleu) [reply infra/odpw/odpw.go:28]: this was the only one that was actually using the log to print a fatal. I will make it panic instead.

File: infra/worker/worker.go (hunk 5 above)
Comment (etuleu) [reply infra/worker/worker.go:39]: this was using log as well. Changed to panic instead.

**Review by jedmccaleb — APPROVED** [review]
